config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :events, only: %i[new index show create]
  resources :users, only: %i[new create show]
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
# frozen_string_literal: true

class Event < ApplicationRecord
  scope :upcoming_scope, -> { where('date >= ?', DateTime.now.to_date) }
  scope :previous_scope, -> { where('date < ?', DateTime.now.to_date) }
  validates :location, presence: true, length: { in: 6..50 }
  validates :description, presence: true, length: { maximum: 255 }
  validates :date, presence: true
  belongs_to :creator, class_name: 'User'
  has_many :event_attendees, foreign_key: :attended_event_id
  has_many :attendees, through: :event_attendees, source: :attendee

  def self.upcoming
    Event.upcoming_scope
  end

  def self.previous
    Event.previous_scope
  end
end

app/models/event_attendee.rb
# frozen_string_literal: true

class EventAttendee < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :attended_event, class_name: 'Event'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :event_attendees, foreign_key: :attendee_id
  has_many :attended_events, through: :event_attendees, source: :attended_event

  validates :name, presence: true, length: { in: 3..20 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze
  validates :email, presence: true, length: { maximum: 244 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  def upcoming_events
    attended_events.where('date >= ?', DateTime.now.to_date)
  end

  def previous_events
    attended_events.where('date < ?', DateTime.now.to_date)
  end

  def my_upcoming_events
    created_events.where('date >= ?', DateTime.now.to_date)
  end

  def my_previous_events
    created_events.where('date < ?', DateTime.now.to_date)
  end

  def self.get_users(user)
    scope :users_scope, -> { where('id != ?', user.id) }
    User.users_scope
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper

  def log_in(user)
    cookies.permanent[:user_id] = user.id
    @currrent_user = user
  end

  def log_out
    cookies.delete(:user_id)
    @currrent_user = nil
  end
end

app/controllers/events_controller.rb
# frozen_string_literal: true

class EventsController < ApplicationController
  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      params[:event][:attendees].each do |attendee|
        unless attendee.blank?
          @event.event_attendees.build(attendee_id: attendee.to_i)
        end
      end
      @event.save
      redirect_to user_path(current_user)
    else
      render 'new'
    end
  end

  def index
    @previous_events = Event.previous
    @upcoming_events = Event.upcoming
  end

  def show
    @event = Event.find(params[:id])
  end

  private

  def event_params
    params.require(:event).permit(:location, :date, :description)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:session][:email])

    if user
      log_in user
      redirect_to user_path(user)
    else
      flash.now[:notice] = 'Email does not exist'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @upcoming_events = @user.upcoming_events
    @previous_events = @user.previous_events
    @my_upcoming_events = @user.my_upcoming_events
    @my_previous_events = @user.my_previous_events
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/events_helper.rb
# frozen_string_literal: true

module EventsHelper
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: cookies[:user_id])
  end

  def current_user=(user)
    @current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def filter_users
    User.get_users(current_user)
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/events/index.html.erb
<div class="event_container">
  <h1>All Events</h1>
  <br>
</div>
<div class="event_container">
  <h2>Upcoming Events</h2>
  <br>
</div>
<div class="event_container">
<% @upcoming_events.each do |event| %>
<div class="event_card">
  <% if event.date %>
    <p class="date_event"> <%= event.date %> <p>
  <% end %>
  <h2> <%= event.location %> <h2>
  <h3> <%= event.description %> <h3>
  <p class="date_event_created"> Posted <%= time_ago_in_words(event.created_at) %> ago</p>
  <%= link_to 'view', event_path(event), class:"date_event"%>
</div>
<% end %>
</div>

<div class="event_container">
  <h2>Previous Events</h2>
  <br>
</div>
<div class="event_container">
<% @previous_events.each do |event| %>
<div class="event_card">
  <% if event.date %>
    <p class="date_event"> <%= event.date %> <p>
  <% end %>
  <h2> <%= event.location %> <h2>
  <h3> <%= event.description %> <h3>
  <p class="date_event_created"> Posted <%= time_ago_in_words(event.created_at) %> ago</p>
  <%= link_to 'view', event_path(event), class:"date_event"%>
</div>
<% end %>
</div>

app/views/events/new.html.erb
<%= form_for @event do |f| %>
  <div>
    <% if @event.errors.any?%>
      <% @event.errors.each do |error|%>
        <p> <%= error %> </p>
      <% end %>
    <% end %>
  </div>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.select(:attendees, filter_users.collect {|p| [ p.name, p.id ] }, 
                                           {}, 
                                           { :multiple => true, :size => 3 }) %>
  <%= f.submit "Create event" %>
<% end %>

app/views/events/show.html.erb
<h2> Created by, <%= @event.creator.name %> </h2>
<h3> <%= @event.location %> <h3>
<h3> Atendees </h3>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li> <%= attendee.name %> </li>
  <% end %>
</ul>

app/views/layouts/_header.html.erb
<header>
  <h2>NewEvents</h2>
  <ul>
    <% if logged_in? %>
    <li><%= link_to 'All events', events_path %></li>
    <li><%= link_to 'New event', new_event_path %></li>
      <li><%= link_to 'Profile', current_user %></li>
      <li><%= link_to 'Logout', logout_path, method: :delete %></li>
    <% else %>
      <li><%= link_to 'Login', login_path %></li>
      <li><%= link_to 'Signup', new_user_path %></li>
    <% end %>
  </ul>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<%= form_with model: @user, class: "nifty_form" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>
  
  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<div class="event_container">
  <h1> Events created by <%= @user.name %> </h1>
</div>
<div class="event_container">
  <h3>Upcoming Events</h3>
  <br>
</div>
<div class="event_container">
<% @my_upcoming_events.each do |event| %>
<div class="event_card">
  <% if event.date %>
    <p class="date_event"> <%= event.date %> <p>
  <% end %>
  <h2> <%= event.location %> <h2>
  <h3> <%= event.description %> <h3>
  <p class="date_event_created"> Posted <%= time_ago_in_words(event.created_at) %> ago</p>
  <%= link_to 'view', event_path(event), class:"date_event"%>
</div>
<% end %>
</div>

<div class="event_container">
  <h3>Previous Events</h3>
  <br>
</div>
<div class="event_container">
<% @my_previous_events.each do |event| %>
<div class="event_card">
  <% if event.date %>
    <p class="date_event"> <%= event.date %> <p>
  <% end %>
  <h2> <%= event.location %> <h2>
  <h3> <%= event.description %> <h3>
  <p class="date_event_created"> Posted <%= time_ago_in_words(event.created_at) %> ago</p>
  <%= link_to 'view', event_path(event), class:"date_event"%>
</div>
<% end %>
</div>

<div class="event_container">
  <h1> Events you were invited to </h1>
</div>
<div class="event_container">
  <h3>Upcoming Events</h3>
  <br>
</div>
<div class="event_container">
<% @upcoming_events.each do |event| %>
<div class="event_card">
  <% if event.date %>
    <p class="date_event"> <%= event.date %> <p>
  <% end %>
  <h2> <%= event.location %> <h2>
  <h3> <%= event.description %> <h3>
  <p class="date_event_created"> Posted <%= time_ago_in_words(event.created_at) %> ago</p>
  <%= link_to 'view', event_path(event), class:"date_event"%>
</div>
<% end %>
</div>

<div class="event_container">
  <h3>Previous Events</h3>
  <br>
</div>
<div class="event_container">
<% @previous_events.each do |event| %>
<div class="event_card">
  <% if event.date %>
    <p class="date_event"> <%= event.date %> <p>
  <% end %>
  <h2> <%= event.location %> <h2>
  <h3> <%= event.description %> <h3>
  <p class="date_event_created"> Posted <%= time_ago_in_words(event.created_at) %> ago</p>
  <%= link_to 'view', event_path(event), class:"date_event"%>
</div>
<% end %>
</div>